// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Naig0NzFxMK-sAiJAO9cl9Cl5JbVwJA',
    appId: '1:649818924107:web:622dc6f5c02ca9619f59ce',
    messagingSenderId: '649818924107',
    projectId: 'al-mobdea-education-platform',
    authDomain: 'al-mobdea-education-platform.firebaseapp.com',
    storageBucket: 'al-mobdea-education-platform.firebasestorage.app',
    measurementId: 'G-SJ8PC15DPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg2gjnOezCRcnwA9fa4bUCG7JAQKB2qNM',
    appId: '1:649818924107:android:eb88d6279c2e93c19f59ce',
    messagingSenderId: '649818924107',
    projectId: 'al-mobdea-education-platform',
    storageBucket: 'al-mobdea-education-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZK3WSE2MvcejfR6pQW-yMHcLDmOOJSDc',
    appId: '1:649818924107:ios:423e30b3f01da29d9f59ce',
    messagingSenderId: '649818924107',
    projectId: 'al-mobdea-education-platform',
    storageBucket: 'al-mobdea-education-platform.firebasestorage.app',
    iosBundleId: 'com.famex.alMobdea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZK3WSE2MvcejfR6pQW-yMHcLDmOOJSDc',
    appId: '1:649818924107:ios:423e30b3f01da29d9f59ce',
    messagingSenderId: '649818924107',
    projectId: 'al-mobdea-education-platform',
    storageBucket: 'al-mobdea-education-platform.firebasestorage.app',
    iosBundleId: 'com.famex.alMobdea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Naig0NzFxMK-sAiJAO9cl9Cl5JbVwJA',
    appId: '1:649818924107:web:99184b1af2fb8e719f59ce',
    messagingSenderId: '649818924107',
    projectId: 'al-mobdea-education-platform',
    authDomain: 'al-mobdea-education-platform.firebaseapp.com',
    storageBucket: 'al-mobdea-education-platform.firebasestorage.app',
    measurementId: 'G-3S0H0MHP27',
  );
}
